//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GpsNotebook.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GpsNotebook.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        internal static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        internal static string LoginMaxChar {
            get {
                return ResourceManager.GetString("LoginMaxChar", resourceCulture);
            }
        }
        
        internal static string LoginMinChar {
            get {
                return ResourceManager.GetString("LoginMinChar", resourceCulture);
            }
        }
        
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string PasswordIncorrect {
            get {
                return ResourceManager.GetString("PasswordIncorrect", resourceCulture);
            }
        }
        
        internal static string PasswordLower {
            get {
                return ResourceManager.GetString("PasswordLower", resourceCulture);
            }
        }
        
        internal static string PasswordMaxChar {
            get {
                return ResourceManager.GetString("PasswordMaxChar", resourceCulture);
            }
        }
        
        internal static string PasswordMinChar {
            get {
                return ResourceManager.GetString("PasswordMinChar", resourceCulture);
            }
        }
        
        internal static string PasswordNotNumber {
            get {
                return ResourceManager.GetString("PasswordNotNumber", resourceCulture);
            }
        }
        
        internal static string PasswordNumber {
            get {
                return ResourceManager.GetString("PasswordNumber", resourceCulture);
            }
        }
        
        internal static string PasswordsMatch {
            get {
                return ResourceManager.GetString("PasswordsMatch", resourceCulture);
            }
        }
        
        internal static string PasswordUpper {
            get {
                return ResourceManager.GetString("PasswordUpper", resourceCulture);
            }
        }
        
        internal static string RegistrationFail {
            get {
                return ResourceManager.GetString("RegistrationFail", resourceCulture);
            }
        }
        
        internal static string RegistrationFailTitle {
            get {
                return ResourceManager.GetString("RegistrationFailTitle", resourceCulture);
            }
        }
        
        internal static string RegistrationSuccessfull {
            get {
                return ResourceManager.GetString("RegistrationSuccessfull", resourceCulture);
            }
        }
        
        internal static string RegistrationSuccessfullTitle {
            get {
                return ResourceManager.GetString("RegistrationSuccessfullTitle", resourceCulture);
            }
        }
        
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        internal static string NameInvalid {
            get {
                return ResourceManager.GetString("NameInvalid", resourceCulture);
            }
        }
        
        internal static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        internal static string AllPins {
            get {
                return ResourceManager.GetString("AllPins", resourceCulture);
            }
        }
        
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }

        internal static string Save
        {
            get
            {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }

        internal static string AddPin
        {
            get
            {
                return ResourceManager.GetString("AddPin", resourceCulture);
            }
        }

        internal static string Label
        {
            get
            {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }

        internal static string Position
        {
            get
            {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }

        internal static string Description
        {
            get
            {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        internal static string Favourite
        {
            get
            {
                return ResourceManager.GetString("Favourite", resourceCulture);
            }
        }

        internal static string Edit
        {
            get
            {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }

        internal static string Delete
        {
            get
            {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }

        internal static string ConfirmationTitle
        {
            get
            {
                return ResourceManager.GetString("ConfirmationTitle", resourceCulture);
            }
        }

        internal static string FieldsFilledError
        {
            get
            {
                return ResourceManager.GetString("FieldsFilledError", resourceCulture);
            }
        }

        internal static string Search
        {
            get
            {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
    }
}
